# Generated by Django 3.0.3 on 2020-02-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0002_auto_20200206_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='finished_at',
            field=models.DateField(null=True),
        ),
    ]
