# Generated by Django 3.0.3 on 2020-02-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0003_auto_20200206_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='finished_at',
            field=models.DateTimeField(null=True),
        ),
    ]
